---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-ngx-admin-credentials
  namespace: paperless-ngx
spec:
  encryptedData:
    password: AgBS/CY6uguVlkPohxalPtHXu+DwF4DVua9QLaiMs2C0vNSAYPCg6cY3lAA2kYDqfuPkA0xQtUP9PoUPRA4DG0HTrz2kltziV2QfIRZWfRPadXwVa5Xdwfi2TJA6iBT+Rra8WnUFDEnLzA9N2zigjuxrOTBjkB1IgWnZgxPTQlmtcbb8xHWkBXQwMmeT8ik7bblCQlbOF3Qz8B3cvgKGUX6aTTCDRvFU5sNV2Z03SH9ZidbMahxVmwSGNLjkn26DjwxZ0jolM+Y6wa8HkFqpNenSgpLzq9vDIAfwll8cjiyijtQ8wYabp6E63wG2pNaik+xQ7BhroH72bakX8ICipSNcCuwyj9JOA5VVDIf/mYOCLCNPDaQVvIF6cBcWCx+JImsrJssMBPNjYI83s1gSc/YYdptnUXdqcZcnM2rt2V3XmQLHstz2GbsY/PvMGs9TmOuwK8Hu8PtBQ45OzWcKkxBtVJEq+95mYgwgchEelPcVZaFbHWalL1nSTKCe/HZe3DHWIcbWKP0pQ4+Ij9QX8d3A/4wL9bHULL3cj3fUxzyPHFk17pQ5Y5xKOEjQ9quV5eBNbzY8Nb6GqrDowTJ9FoQK2rbDhTO4e3RESu2xJ5/OXN1fOBLHPqhTHzMfci1R1arBSDHAz9Z6jRPOcqARfKA2cnBlV1+/DsNF7seB4s36gcsefbN/fJN/7KbVNLcvYBXwLUdbgne3pq4BbdRwXQfaAPTo6w==
    username: AgBEOmyDei/HLRCPU/S3wURkCfeiqMQdUX31aT3aEOTQZSRcSQBzgMj+gf84f4AYOAS8CE/kDgNBPkltkrcZmRfz1gJmz6igq6eJyXU53eC4RPORLwiloPyzvBJmD4NEGsqIqVnluW+qV/KLqVZl+m38WdnvP4/iC1Ue/HjNz+q24AUgOok+Ylzxp3wZKhJp8dUa1HGSQ9wOq9Qr7oP+57ywKZg7sUAHVbiPz9uVaH6zfIYfO4iClxqNi6px4hrMHMsmm09GPQcuADg+MIfRunTkO5ZvLfuPSNdTdypKN38Mwt79+ykaVBruV9502ULfV9UCHiSe3IHS+g0t+OtAFt74unvj1Dieh7K76jP9saSFDA26q4OTObK5XbmiqRxuQqsZ5Cev0P0vJ0EQK7MN9GGm/i4Iabo+ZLae9Y0ZKfjrvAkmlGXXD89nenwmrLNzjxPLIyzRad4aELVbKHTrAUiXpkG5Q+Xi11aCFyWzGQ5C1gmykppyqCQxpsHXiPC8VYdG0wH2RhTFyzi+yRFvo0zGWMu7gw1jk7Eq1mPhug0SX8eunKOpVgWnqPs2JmIpJOY9dI6fsC7EAwXlBT4QtpA1CLtGMybCU5nlg8OXeIVFq0xMZlJZQSdxPItEbDsypZhJRZhx469fTzlbgHrY594g13gH6goV+yt68c7Ezcq5Dnkz/6BT/ZZt8pKQF2bD09071+PAYtyCrHQ=
  template:
    metadata:
      creationTimestamp: null
      name: paperless-ngx-admin-credentials
      namespace: paperless-ngx
    type: Opaque
