---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-ngx-db-credentials
  namespace: paperless-ngx
spec:
  encryptedData:
    password: AgC3Bl2REoVaAg/xDvGDPNgMLJE0Qh3LsFq4B6derdTEFnsawU1AtNHK012I9q2j3ZlpyZGeB/eG4FqvStS1o3Eeqpxgio3wtKJausMbXE3M2UOMQ3PUX4C5VHXIQcgctQDCtEJDv6q0tJUEeK3u+QnoUM79jqqwTVDv+mE3J68BRPOTs1QZY4mrqYu603l2LLhinnzQ5dArVg4Gfa+Ubvo2U1zm0wffqGiz7eHzMQkQafjJ1cwwNx4VKHR+VyxREqoz/ZpHHmlXkAParUtsZw1QpDT/P0Q1yjzcl17onoRDYHz7WNZXAIbJ6uhLVwlHf2HAMkupNkntCNU0gut7fO98AqfVaWeG+rdWF1e/AqGM1D3VpMo6Vd3wrFeBTiZxYxmOQBpb0Y4fCfHTvblI2SZYm47WchXWKHphH7lrwW2kDTQdia6TbQyXX/7IVoP0cGmoqZcVDMnZKp2A6s5d7ABbOw1t1zWD6ztCJhqjRTEvQ0BMY9N+iCpT9qiKn0QRfHyL39U2Tld4E1P14Ae08kEJDjzjw35WkPmcB2wdVlsYmdum2YkxlpUXqp8L94lGGDYBndY5tMjL2v1VPT6jdkWmxI7QEzgdUvJZHNk6Zp81otTpaV41AggTbAloK4/n8de9z7j2pXpqKMVDQlblFdajZ6AiTFcmnegy2Rx6q2xDZgEZgkEFr389prbx4oatF+nguLHszoPJvmQr6bnyxRy1R7SAUw==
    username: AgBlf4YH1/x77/rMcv1+tdhxcoV/3dnWLst8XaXI0MZFVodAUpJ4duq9utVDYO7xNdbN+NDTUd4LWRIr5WL6KGCa6rIVdC1S9fGWoRrgn3pQtmirjr8NO1so7L1IrPcG2V6zeH+6/DKB7/+ECXjSIjnNTbgVBJlxhPG0TJzItVwzHa0XiU/FXCS9HcigA10w6DBYsct2kt+jZsAB2WocYWz4b0mCHXm0+SeVgaJthT14x8c8yHw1/HeFWPj/7Yp88KwMGJ2kFiuzi1PnDVbqtsSHcOClxL4j5yGnJKdBAb63B+QzMJCNllaNlGzKUPTsVNCxtgVvtdOaT8xfrWoSN40WsYa7Sof9bOo21Wgo8EzV+YgfZz4TD1pSDXjG+N9+V46C4xAKDVqepxWLlq8cOxTHu4lWwqq3PZoA9vWhqOc6dnOmA7T55l9KIBbyhFTanCpS58DvJJ7EmE0e/9wRClT37Ukn1nsXRpC7/skPB7bxWUCWlm7pD+5g+piFnxUFDhD9jBRLgOJQ1qlyOsfqCgh57jGIm8tAx9Dxmqsx3+epj3/+9MC8BpSitgz3WWZquRYqrnbGG1FT0SUWFSthvOTZIzBT/1GMNu/vbLd+1pVku8bu+6elaqqeyMp/ecIydKKTfnpwI/Dqx7CJK+USjMyeu4R3vchJc4T17am2IMaopxqUlvXnwzRgtcsE2T2Xn743bWD3ZGTTeXc=
  template:
    metadata:
      creationTimestamp: null
      name: paperless-ngx-db-credentials
      namespace: paperless-ngx
    type: Opaque
