---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-ngx-valkey-credentials
  namespace: paperless-ngx
spec:
  encryptedData:
    password: AgBpIrXkYYv6JBFrJi8wwSYcYFDPzMgoLaBC3MnutI6KH7p3UiRVOp+PTNtuvddbHiJ2vphWBm0gHwBN7MOqyZU44kZh2DjUf8mGwgZTiQMJA4nsyaLGIdBFljLgbMN6D93XvucusVB3E5rRZck5pS19BWX3v59JyNpx0YP9grH9gbzv9aZ6QtrAZWV/NzQXzYfbbyjOyscf2yn0+udbG9gnBh9jaiCUxt+8MeaQbOZMdSfuwcpiL0sM57RK1eiZ0uz1cWQkBusAB2JybZ3NcP8X/DzsMTEGnsj7AILBgFboHn4QCJh3EB+oOXk1k53fS2yDZdofTKMLNeOAiiieVSXO9DCmWOWwHe2yUlDMrEVthjZiAlbgNAcUNwMFFXv5Dyn1kgUnPM//CE0IL2TnvpbaWx6TMbdahmsekwccPjJo0ZLVSvrmn8CZ67uBMvlLhYWNao+ppzbownTD+P5upCcrSxm9fcuvRl4FNo9O9evCgo2IdaS8/S3d2UHWk83FZIt6Aj0zU/aQ/dVcRAtVGFFWtoAcv09chDGRw9+CHq0OhsyUeyN38oxvcM/si0jxOh/XdJOXAlmqSHsujNNcqQa34V+24qITrjUVyq7JApOVnOeMxqAP1oN9tOxdLHebbzHchQTpvoQaBipNa0Z+f6eXjC+nMYspuo7J0QqvncbqFDBNUOtoK2Kh929omugnKK0GQV+78rEdNyiTQHyXkwmiaFjbHA==
    url: AgCM7fJJU7yVih+STqthMHfFILcWk+UWtd+yGGR/NHtnBkkR7DnNiq4M7R9a44kt3+u3MUJvYTFxcGgJ0+di5VMdu4dDK4OedDJZh0LDU2csAdMmPXHVLsCDxHgmrcZSCO34GcDG6dfeCpdP20Qq5thOLxFaGLPdB3C5R9Tu6WbaNZashPf2ciWbF7mQixmUupWwyz8o9cC/jidvALUxN6rSxkHLECYjf8Q1czJisD9pd+J4B9xzSija0hiq8vArQQsK930ET3uNyJ6Gou/bxPZ54KTMZrr7R2Mkb0Eam4HJxksGZu97gsUVc/iOpwZav2Kih7QpVgLpcTOWsHLbyZAc371GkIAGUtdUyNDXAG1vcWOFwJiF4PUa7u7Pw/EWhTMD4WuL8qn83EUjS/HxAghEhngqeFWwoIaWJgW3UleZ6RAeUC+M5xHVCW0n6fKeB8XNOUASv90o3kBpd9KW0e31LTkGQuwZ2riVgPk08byqqDPlanCvtYRWEz7qxuNiAT+HPLvtD7e+21L0wMiEKigUfiTuWsbR/lmNHkbOEYLpVIT7fAYsKEGVU32V30YfFYbGxe4I03KX55assFDya2opQlmEDNlwFD/mgxAdXA7MGvnfJ+b+5pB2HEDy6dcgr+DGNJg5jxxJnjykeSM7QpuKGn69CWNLsvyjjQinwnrxZ3ZUDSlzyC/8Lb0zpyC8I7ApQP3JJjF4NW1GAGn4JyddIH2rQJ8TUsVR2Da28w6cYE33sJwvIes/REzRn38OJwS5t5urLpxF
  template:
    metadata:
      creationTimestamp: null
      name: paperless-ngx-valkey-credentials
      namespace: paperless-ngx
    type: Opaque
